spring.application.name=assembly-vote
doc-application.description=Avaliacao tecnica SICRED
doc-application.version=v1

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.path=swagger-ui.html

spring.datasource.url=${DATASOURCE_URL:jdbc:oracle:thin:@//localhost:1521/assemblyvote}
spring.datasource.username=${DATASOURCE_USER:appuser}
spring.datasource.password=${DATASOURCE_PASSWORD:passwd}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-description=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.type=redis

application.session-duration-sec.default=60
scheduler.voting.close-delay=10000